name: AutoBuild .NET

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget unzip -y

      - name: Download and Unzip BepInEx
        run: |
          wget https://builds.bepinex.dev/projects/bepinex_be/697/BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.697%2B5362580.zip -O BepInEx.zip
          unzip BepInEx.zip -d ./Release/
          sudo chmod -R 777 ./Release

      - name: Download and Unzip ExtraData
        run: |
          wget https://raw.githubusercontent.com/mxyx-club/ExtraData/main/ExtraData.zip -O ExtraData.zip
          unzip ExtraData.zip -d ./Release/

      - name: Download Reactor
        run: wget https://github.com/NuclearPowered/Reactor/releases/download/2.2.0/Reactor.dll -P ./Release/BepInEx/plugins
        
      - name: Build
        run: dotnet build TheOtherRoles/TheOtherRoles.csproj --configuration Beta --output ./Release/BepInEx/plugins

      - name: Cleanup
        run: |
          rm -rf ./Release/BepInEx/plugins/TheOtherUs.deps.json
          rm -rf ./Release/BepInEx/plugins/TheOtherUs.pdb
          rm -rf ./Release/changelog.txt
          
      - name: Upload TheOtherUsDll
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TheOtherUs.dll
          path: ./Release/BepInEx/plugins/TheOtherUs.dll
          
      - name: Upload TheOtherUs
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TheOtherUs
          path: ./Release/
